types:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - chore: Other changes that don't modify src or test files

scopes:
  all:
    - core
    - rss
    - cron
    - todo
    - gradle
    - project
  docs:
    - readme
  chore:
    - build
    - ci
    - deps
    - tools

options:
  allowBreakingChanges:
    - feat
    - fix
  allowIssues:
    - feat
    - fix
